# docker-compose.yml

version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - portal
      - backend
    restart: unless-stopped

  portal:
    build:
      context: ./portal
    container_name: portal-app
    ports:
      - "9000:9000"
    env_file:
      - ./portal/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: express-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
